# Generated by Django 5.0.6 on 2024-07-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='img_path',
        ),
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='./media/ads'),
        ),
    ]
