# Generated by Django 5.0.6 on 2024-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0002_remove_advert_img_path_advert_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='image',
        ),
        migrations.AddField(
            model_name='advert',
            name='image_path',
            field=models.FilePathField(default='/ad1', path='./media/ads', unique=True),
        ),
    ]
