# Generated by Django 4.1.13 on 2024-06-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_alter_rank_reward_id_alter_stage_rank_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.reward'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.reward'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.reward'),
        ),
    ]
