# Generated by Django 4.1.13 on 2024-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdata", "0005_alter_rank_reward_id_alter_stage_reward_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reward",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="stage",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
