# Generated by Django 5.0.6 on 2024-06-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_alter_rank_name_alter_reward_name_alter_stage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rank_id',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.rank'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='stage_id',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='userdata.stage'),
        ),
    ]
