# Generated by Django 5.0.6 on 2024-06-21 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_alter_userdata_rank_id_alter_userdata_stage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='next_rank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_rank_from_rank', to='userdata.rank'),
        ),
        migrations.AddField(
            model_name='stage',
            name='next_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_rank_from_stage', to='userdata.rank'),
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_stage_from_stage', to='userdata.stage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tasks_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userdata.task'),
        ),
    ]
