# Generated by Django 5.0.6 on 2024-06-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0008_rank_next_rank_stage_next_rank_stage_next_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='next_rank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_rank_from_rank', to='userdata.rank'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='next_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_rank_from_stage', to='userdata.rank'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_stage_from_stage', to='userdata.stage'),
        ),
    ]
