# Generated by Django 5.0.6 on 2024-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_alter_rank_next_rank_alter_stage_next_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='tasks_id',
        ),
        migrations.AddField(
            model_name='stage',
            name='tasks_id',
            field=models.ManyToManyField(blank=True, null=True, to='userdata.task'),
        ),
    ]
