# Generated by Django 5.0.6 on 2024-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0010_remove_stage_tasks_id_stage_tasks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='tasks_id',
            field=models.ManyToManyField(to='userdata.task'),
        ),
    ]
