
services:
    app:
        build:
          context: .
        container_name: backend_app_service
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   gunicorn app.wsgi:application --bind 0.0.0.0:8000"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        container_name: db_service
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        env_file:
            - .env
        volumes:
            - dev-db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    nginx:
        build: ./nginx
        container_name: nginx_service
        ports:
            - 80:80
        depends_on:
            - app

volumes:
    dev-db-data: