
services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   gunicorn app.wsgi:application --bind 0.0.0.0:8000"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        ports:
            - "5432:5432"
        volumes:
            - dev-db-data:/var/lib/postgresql/data

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - app

    ngrok:
        build:
          context: .
          dockerfile: Dockerfile.ngrok
        ports:
          - "4040:4040"
        depends_on:
          - app
        environment:
          - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
          - NGROK_PORT=app:${NGROK_PORT}

volumes:
    dev-db-data: