
services:
    app:
        build:
          context: .
          args:
            - DEV=true
        container_name: bwg_combat_backend_app
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"

        environment:
            - DB_HOST=db
            - DB_NAME=bwg_combat_mongo_db
            - DB_USER=root
            - DB_PASS=root
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        container_name: bwg_combat_db
        environment:
          - POSTGRES_DB=bwg_combat_mongo_db
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
        volumes:
          - dev-db-data:/var/lib/postgresql/data
        ports:
          - 5432:5432

volumes:
    dev-db-data: