# Generated by Django 5.0.6 on 2024-07-11 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completedsocialtasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maxenergylevel',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.maxenergylevel'),
        ),
        migrations.AddField(
            model_name='multiclicklevel',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.multiclicklevel'),
        ),
        migrations.AddField(
            model_name='passiveincomelevel',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.passiveincomelevel'),
        ),
        migrations.AddField(
            model_name='rank',
            name='init_energy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.maxenergylevel'),
        ),
        migrations.AddField(
            model_name='rank',
            name='init_multiplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.multiclicklevel'),
        ),
        migrations.AddField(
            model_name='rank',
            name='inviter_reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward'),
        ),
        migrations.AddField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.stage'),
        ),
        migrations.AddField(
            model_name='rank',
            name='init_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.stage'),
        ),
        migrations.AddField(
            model_name='taskroutes',
            name='subtasks',
            field=models.ManyToManyField(to='levels_app.taskroutes'),
        ),
        migrations.AddField(
            model_name='stage',
            name='initial_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ini_task', to='levels_app.taskroutes'),
        ),
        migrations.AddField(
            model_name='stage',
            name='tasks',
            field=models.ManyToManyField(related_name='stage', to='levels_app.taskroutes'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='rewards',
            field=models.ManyToManyField(to='levels_app.reward'),
        ),
        migrations.AddField(
            model_name='taskroutes',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.tasktemplate'),
        ),
    ]
