# Generated by Django 5.0.6 on 2024-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskroutes',
            name='subtasks',
            field=models.ManyToManyField(blank=True, to='levels_app.taskroutes'),
        ),
    ]
