# Generated by Django 5.0.6 on 2024-07-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0005_alter_stage_options_alter_stagetemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedsocialtasks',
            options={'verbose_name_plural': '9.2_Completed_Out_Rank_Tasks model'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': '9.1_Out_Rank_Tasks model'},
        ),
    ]
