# Generated by Django 5.0.6 on 2024-07-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0006_alter_completedsocialtasks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagetemplate',
            options={'verbose_name_plural': '2.1_StageTemplate model'},
        ),
    ]
