# Generated by Django 5.0.6 on 2024-07-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0007_alter_stagetemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagetemplate',
            options={'verbose_name_plural': '2.1_StageTemplate models'},
        ),
    ]
