# Generated by Django 5.0.6 on 2024-07-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0008_alter_stagetemplate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskroutes',
            name='subtasks',
        ),
        migrations.AddField(
            model_name='taskroutes',
            name='subtasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.taskroutes'),
        ),
    ]
