# Generated by Django 5.0.6 on 2024-07-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0011_stage_stage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='name',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
