# Generated by Django 5.0.6 on 2024-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0017_stagetemplate_jail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('1', 'Add gold'), ('2', 'Increase gold multiplier'), ('3', 'Add G token'), ('4', 'Replenish energy'), ('5', 'Improve passive income'), ('6', 'Key'), ('7', 'Gnome'), ('8', 'Jail')], default='1', null=True),
        ),
    ]
