# Generated by Django 5.0.6 on 2024-07-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0020_alter_taskroutes_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='has_keylock',
            field=models.BooleanField(default=True),
        ),
    ]
