# Generated by Django 5.0.6 on 2024-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0022_remove_stagetemplate_has_keylock_stage_has_keylock'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='swap_limit',
            field=models.IntegerField(default=10),
        ),
    ]
