# Generated by Django 5.0.6 on 2024-08-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0023_partnersocialtasks_delete_socialmedia_and_more'),
        ('levels_app', '0023_rank_swap_limit'),
    ]

    operations = [
    ]
