# Generated by Django 5.0.6 on 2024-08-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0024_merge_20240801_1840'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersButtonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='Register', max_length=64)),
                ('name_de', models.CharField(default='Register', max_length=64)),
                ('name_fr', models.CharField(default='Register', max_length=64)),
                ('name_ru', models.CharField(default='Register', max_length=64)),
                ('name_uk', models.CharField(default='Register', max_length=64)),
                ('name_zh', models.CharField(default='Register', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SocialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64)),
                ('name_de', models.CharField(max_length=64)),
                ('name_fr', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_uk', models.CharField(max_length=64)),
                ('name_zh', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=1024)),
                ('reward_amount', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='partnersocialtasks',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='partnersocialtasks',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='partnersocialtasks',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='partnersocialtasks',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='partnersocialtasks',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='partnersocialtasks',
            name='name_zh',
        ),
        migrations.CreateModel(
            name='PartnersTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=1024)),
                ('reward_amount', models.BigIntegerField()),
                ('button_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.partnersbuttontypes')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedPartnersTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.partnerstasks')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedSocialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.socialtasks')),
            ],
        ),
        migrations.DeleteModel(
            name='CompletedPartnersSocialTasks',
        ),
    ]
