# Generated by Django 5.0.6 on 2024-08-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0025_partnersbuttontypes_socialtasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='init_energy',
        ),
        migrations.RemoveField(
            model_name='multiclicklevel',
            name='next_level',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='init_multiplier',
        ),
        migrations.RemoveField(
            model_name='passiveincomelevel',
            name='next_level',
        ),
        migrations.RemoveField(
            model_name='taskroutes',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='taskroutes',
            name='template',
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name_plural': 'Ranks'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name_plural': 'Rewards'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name_plural': 'Stages'},
        ),
        migrations.AlterModelOptions(
            name='stagetemplate',
            options={'verbose_name_plural': 'StageTemplates'},
        ),
        migrations.AlterModelOptions(
            name='tasktemplate',
            options={'verbose_name_plural': 'TaskTemplates'},
        ),
        migrations.AlterField(
            model_name='rank',
            name='gold_required',
            field=models.BigIntegerField(default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='inviter_reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.reward'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='next_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.rank'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('1', 'Add gold'), ('3', 'Add G token'), ('2', 'Increase gold multiplier'), ('4', 'Replenish energy'), ('5', 'Key'), ('6', 'Gnome'), ('7', 'Jail')], default='1'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='next_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.stagetemplate'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='completion_number',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='task_type',
            field=models.CharField(choices=[('1', 'subscribe to channel'), ('2', 'invite friend'), ('3', 'earn N amount of gold'), ('4', 'buy energy balance'), ('5', 'buy multiclick'), ('6', 'buy chest')], default='6'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EnergyBalanceUpgradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.energybalanceupgradelevel')),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='init_energy_balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.energybalanceupgradelevel'),
        ),
        migrations.CreateModel(
            name='MulticlickUpgradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.multiclickupgradelevel')),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='init_multiclick',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.multiclickupgradelevel'),
        ),
        migrations.CreateModel(
            name='PassiveIncomeUpgradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.passiveincomeupgradelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField(default=0)),
                ('coord_y', models.IntegerField(default=0)),
                ('initial', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='levels_app.taskroute')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.tasktemplate')),
            ],
            options={
                'verbose_name_plural': 'TaskRoutes',
            },
        ),
        migrations.AlterField(
            model_name='stage',
            name='initial_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ini_task', to='levels_app.taskroute'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tasks',
            field=models.ManyToManyField(related_name='stage', to='levels_app.taskroute'),
        ),
        migrations.AlterField(
            model_name='stagetemplate',
            name='task_with_keys',
            field=models.ManyToManyField(to='levels_app.taskroute'),
        ),
        migrations.DeleteModel(
            name='MaxEnergyLevel',
        ),
        migrations.DeleteModel(
            name='MulticlickLevel',
        ),
        migrations.DeleteModel(
            name='PassiveIncomeLevel',
        ),
    ]
