# Generated by Django 5.0.6 on 2024-08-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0025_partnersbuttontypes_socialtasks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerSocialTasks',
        ),
    ]
