# Generated by Django 5.0.6 on 2024-08-07 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
        ('levels_app', '0027_delete_taskroutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='init_energy_balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='clicker_app.energybalanceupgradelevel'),
        ),
        migrations.RemoveField(
            model_name='multiclickupgradelevel',
            name='next_level',
        ),
        migrations.AlterField(
            model_name='rank',
            name='init_multiclick',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='clicker_app.multiclickupgradelevel'),
        ),
        migrations.RemoveField(
            model_name='passiveincomeupgradelevel',
            name='next_level',
        ),
        migrations.AlterField(
            model_name='rank',
            name='init_energy_regeneration',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='EnergyBalanceUpgradeLevel',
        ),
        migrations.DeleteModel(
            name='MulticlickUpgradeLevel',
        ),
        migrations.DeleteModel(
            name='PassiveIncomeUpgradeLevel',
        ),
    ]
