# Generated by Django 5.0.6 on 2024-08-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0002_remove_energybalanceupgradelevel_amount_and_more'),
        ('levels_app', '0028_alter_rank_init_energy_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clicker_app.energybalanceupgradelevel'),
        ),
        migrations.AddField(
            model_name='stage',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clicker_app.multiclickupgradelevel'),
        ),
    ]
