# Generated by Django 5.0.6 on 2024-08-07 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0029_stage_drink_stage_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='init_energy_balance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rank',
            name='init_multiclick',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
