# Generated by Django 5.0.6 on 2024-08-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0026_delete_partnersocialtasks'),
        ('levels_app', '0030_alter_rank_init_energy_balance_and_more'),
    ]

    operations = [
    ]
