# Generated by Django 5.0.6 on 2024-08-08 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0031_merge_20240808_1302'),
        ('links_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('reward_amount', models.BigIntegerField()),
                ('button_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.partnersbuttontypes')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links_app.linkmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SocialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=64)),
                ('name_de', models.CharField(max_length=64)),
                ('name_fr', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_uk', models.CharField(max_length=64)),
                ('name_zh', models.CharField(max_length=64)),
                ('reward_amount', models.BigIntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links_app.linkmodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='partnerstasks',
            name='button_type',
        ),
        migrations.RenameModel(
            old_name='CompletedPartnersTasks',
            new_name='CompletedPartnersTask',
        ),
        migrations.AlterField(
            model_name='completedpartnerstask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.partnerstask'),
        ),
        migrations.RenameModel(
            old_name='CompletedSocialTasks',
            new_name='CompletedSocialTask',
        ),
        migrations.AlterField(
            model_name='completedsocialtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.socialtask'),
        ),
        migrations.DeleteModel(
            name='PartnersTasks',
        ),
        migrations.DeleteModel(
            name='SocialTasks',
        ),
    ]
