# Generated by Django 5.0.6 on 2024-07-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=1.0)),
                ('asset_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates_sell', to='exchanger_app.asset')),
                ('asset_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates_buy', to='exchanger_app.asset')),
            ],
        ),
    ]
