# Generated by Django 5.0.6 on 2024-07-11 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanger_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchanger_app.asset'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_giving', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_receiving', to=settings.AUTH_USER_MODEL),
        ),
    ]
