# Generated by Django 5.0.6 on 2024-07-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0002_exchangerate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeRate',
            new_name='ExchangePair',
        ),
    ]
