# Generated by Django 5.0.6 on 2024-07-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstasks',
            old_name='complete_time',
            new_name='completion_time',
        ),
        migrations.RemoveField(
            model_name='userstasks',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='userstasks',
            name='start_time',
        ),
    ]
