# Generated by Django 5.0.6 on 2024-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='click_multiplier',
            new_name='click_multiplier_level',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='energy',
            new_name='energy_level',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='passive_income',
            new_name='passive_income_level',
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='complete_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
