# Generated by Django 5.0.6 on 2024-06-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interface_lang",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.language",
                to_field="lang_code",
            ),
        ),
    ]
