# Generated by Django 5.0.6 on 2024-07-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='userstasks',
        #     name='status',
        # ),
        migrations.AlterField(
            model_name='user',
            name='interface_lang',
            field=models.ForeignKey(default='en', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='user_app.language', to_field='lang_code'),
        ),
    ]
