# Generated by Django 5.0.6 on 2024-07-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_userstasks_status'),
        ('user_app', '0002_remove_userstasks_status_alter_user_interface_lang'),
    ]

    operations = [
    ]
