# Generated by Django 5.0.6 on 2024-07-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='lang_code',
            field=models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian'), ('fr', 'French'), ('de', 'Deutsche')], default='en'),
        ),
    ]
