# Generated by Django 5.0.6 on 2024-06-23 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_interface_lang_fren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fren',
            name='inviter_tg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
