# Generated by Django 5.0.6 on 2024-06-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_interface_lang'),
        ('user_app', '0002_alter_user_interface_lang_fren'),
    ]

    operations = [
    ]
