# Generated by Django 5.0.6 on 2024-07-03 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0005_alter_multiplierlevel_id_alter_passiveincomelevel_id'),
        ('user_app', '0003_merge_20240702_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='click_multiplier',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Click_level', to='levels_app.multiplierlevel'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='energy',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.energylevel'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='passive_income',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_level', to='levels_app.passiveincomelevel'),
        ),
    ]
