# Generated by Django 4.1.13 on 2024-06-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
