# Generated by Django 5.0.6 on 2024-07-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userdata_lang_code'),
        ('user_app', '0004_alter_link_task'),
    ]

    operations = [
    ]
