# Generated by Django 5.0.6 on 2024-07-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_userstasks_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='current_energy',
            field=models.IntegerField(default=0),
        ),
    ]
