# Generated by Django 5.0.6 on 2024-06-24 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_alter_fren_inviter_tg_id"),
        ("user_app", "0004_alter_user_interface_lang_userdata"),
    ]

    operations = []
