# Generated by Django 5.0.6 on 2024-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_remove_userstasks_status_userdata_current_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='character_gender',
            field=models.BooleanField(blank=True, default=None, help_text='True - male, False - female', null=True),
        ),
    ]
