# Generated by Django 5.0.6 on 2024-06-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_merge_20240624_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='click_multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
