# Generated by Django 5.0.6 on 2024-07-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_merge_0003_userdata_lang_code_0004_alter_link_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='lang_code',
        ),
    ]
