# Generated by Django 5.0.6 on 2024-07-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_user_id_userdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstasks',
            old_name='reward',
            new_name='rewards',
        ),
    ]
