# Generated by Django 5.0.6 on 2024-06-25 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_merge_20240624_1047"),
        ("user_app", "0005_merge_20240624_1234"),
    ]

    operations = []
