# Generated by Django 5.0.6 on 2024-07-08 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0003_rename_multiplierlevel_maxenergylevel_and_more'),
        ('user_app', '0006_remove_userdata_lang_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='click_multiplier_level',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='energy_level',
        ),
        migrations.AddField(
            model_name='userdata',
            name='max_energy_level',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.maxenergylevel'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='multiclick_level',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Click_level', to='levels_app.multiclicklevel'),
        ),
    ]
