# Generated by Django 5.0.6 on 2024-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_userstasks_status_userdata_character_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='character_gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], default=None, null=True),
        ),
    ]
