# Generated by Django 4.1.13 on 2024-06-19 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lang_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lang_code', models.CharField(max_length=2, unique=True)),
                ('lang_name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_lang',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, to='user_app.language', to_field='lang_code'),
        ),
    ]
