# Generated by Django 5.0.6 on 2024-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_userdata_click_multiplier_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='max_energy_level',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='multiclick_level',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
