# Generated by Django 5.0.6 on 2024-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_alter_user_interface_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="energy",
            field=models.BigIntegerField(default=100),
        ),
    ]
