# Generated by Django 5.0.6 on 2024-07-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_userstasks_status_and_more'),
    ]

    operations = [
    ]
