# Generated by Django 5.0.6 on 2024-07-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_userdata_passive_income_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='passive_income_level',
            new_name='gnome_amount',
        ),
    ]
