# Generated by Django 5.0.6 on 2024-07-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_userdata_max_energy_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='max_energy_level',
            new_name='max_energy_amount',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='multiclick_level',
            new_name='multiclick_amount',
        ),
    ]
