# Generated by Django 5.0.6 on 2024-07-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0008_alter_maxenergylevel_id_alter_multiclicklevel_id_and_more'),
        ('user_app', '0009_rename_max_energy_level_userdata_max_energy_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersTasks',
            new_name='UsersTask',
        ),
    ]
