# Generated by Django 5.0.6 on 2024-07-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_rename_passive_income_level_userdata_gnome_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='effects_volume',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='general_volume',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='music_volume',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='visual_effects',
            field=models.BooleanField(default=True),
        ),
    ]
