# Generated by Django 5.0.6 on 2024-06-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_merge_20240625_1013'),
        ('user_app', '0010_user_tasks'),
    ]

    operations = [
    ]
