# Generated by Django 5.0.6 on 2024-06-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_fren_fren_tg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fren',
            old_name='fren_tg_id',
            new_name='fren_tg',
        ),
        migrations.RenameField(
            model_name='fren',
            old_name='inviter_tg_id',
            new_name='inviter_tg',
        ),
        migrations.AlterUniqueTogether(
            name='fren',
            unique_together={('fren_tg', 'inviter_tg')},
        ),
    ]
