# Generated by Django 5.0.6 on 2024-06-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_rename_user_tasks_userstasks_alter_user_tg_username'),
        ('user_app', '0020_alter_user_tg_username'),
    ]

    operations = [
    ]
