# Generated by Django 5.0.6 on 2024-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_merge_20240628_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='bot_multitap',
        ),
        migrations.AddField(
            model_name='userdata',
            name='passive_income',
            field=models.BigIntegerField(default=100, help_text='coins per hour'),
        ),
    ]
