# Generated by Django 5.0.6 on 2024-06-28 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0007_alter_reward_reward_type'),
        ('user_app', '0021_merge_20240628_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rank_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.rank'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='stage_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.stage'),
        ),
    ]
