# Generated by Django 5.0.6 on 2024-06-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_alter_userdata_rank_id_alter_userdata_stage_id'),
        ('user_app', '0024_rename_user_id_linkclick_user'),
    ]

    operations = [
    ]
