# Generated by Django 5.0.6 on 2024-07-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0011_task_completion_number_alter_rank_reward_id_and_more'),
        ('user_app', '0025_merge_20240630_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.task'),
        ),
    ]
