# Generated by Django 5.0.6 on 2024-06-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0012_rename_fist_stage_rank_first_stage'),
        ('user_app', '0025_merge_20240629_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstasks',
            unique_together={('user', 'task')},
        ),
    ]
