# Generated by Django 5.0.6 on 2024-07-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_userstasks_status_alter_userstasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='status',
        ),
    ]
