# Generated by Django 5.0.6 on 2024-07-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_merge_20240630_1414'),
        ('user_app', '0026_alter_userstasks_unique_together'),
    ]

    operations = [
    ]
