# Generated by Django 5.0.6 on 2024-07-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_merge_20240701_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.task'),
        ),
    ]
