# Generated by Django 5.0.6 on 2024-07-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_userstasks_status_alter_userstasks_task'),
        ('user_app', '0028_alter_userstasks_task'),
    ]

    operations = [
    ]
