# Generated by Django 5.0.6 on 2024-08-08 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField()),
                ('total_count', models.IntegerField()),
                ('win', models.IntegerField()),
                ('win_count_min', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('lost_count_min', models.IntegerField()),
                ('if_not_enough', models.BooleanField()),
                ('amount_attempted', models.IntegerField()),
                ('gnome_chance', models.IntegerField()),
                ('gnome_chance_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.IntegerField()),
                ('result', models.CharField(max_length=16)),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mini_games_app.levelinfo')),
            ],
        ),
    ]
