# Generated by Django 5.0.6 on 2024-08-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_games_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresults',
            old_name='level_id',
            new_name='level',
        ),
    ]
