# Generated by Django 5.0.6 on 2024-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_games_app', '0002_rename_level_id_gameresults_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelinfo',
            name='amount_attempted',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='gnome_chance',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='gnome_chance_max',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='if_not_enough',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='lost',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='lost_count_min',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='win',
        ),
        migrations.RemoveField(
            model_name='levelinfo',
            name='win_count_min',
        ),
        migrations.AlterField(
            model_name='gameresults',
            name='result',
            field=models.CharField(max_length=32),
        ),
    ]
