# Generated by Django 5.0.6 on 2024-08-09 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_games_app', '0004_gamestarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresults',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamestarted',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
