# Generated by Django 5.0.6 on 2024-08-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkclick',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links_app.link'),
        ),
    ]
