# Generated by Django 5.0.6 on 2024-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='data',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='link_type',
            field=models.CharField(choices=[('TELEGRAM_CHANEL', 'Telegram Chanel'), ('TELEGRAM_OTHER', 'Telegram Other'), ('OTHER', 'Other')], default='OTHER'),
        ),
    ]
