# Generated by Django 5.0.6 on 2024-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0015_alter_reward_name_alter_reward_reward_type'),
        ('user_app', '0002_rename_complete_time_userstasks_completion_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='reward',
        ),
        migrations.AddField(
            model_name='userstasks',
            name='reward',
            field=models.ManyToManyField(blank=True, null=True, to='levels_app.reward'),
        ),
    ]
