# Generated by Django 5.0.6 on 2024-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_reward_userstasks_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='blocked_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
