# Generated by Django 5.0.6 on 2024-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_userdata_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='passive_income_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
