# Generated by Django 5.0.6 on 2024-07-17 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_userdata_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='blocked_until',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
