# Generated by Django 5.0.6 on 2024-08-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_userdata_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='status',
            field=models.CharField(choices=[('0', 'Unavailable'), ('1', 'In progress'), ('4', 'Not claimed'), ('2', 'Claimed'), ('3', 'Expired')], default='0'),
        ),
    ]
