# Generated by Django 5.0.6 on 2024-08-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0009_alter_banneradvert_link_alter_fullscreenadvert_link_and_more'),
        ('user_app', '0014_userdata_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkclick',
            name='link',
        ),
        migrations.RemoveField(
            model_name='linkclick',
            name='user',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='LinkClick',
        ),
    ]
