# Generated by Django 5.0.6 on 2024-08-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0026_remove_rank_init_energy_and_more'),
        ('user_app', '0015_alter_userstasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels_app.taskroute'),
        ),
    ]
