# Generated by Django 5.0.6 on 2024-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_linkclick_link_remove_linkclick_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
