# Generated by Django 5.0.6 on 2024-08-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_userstasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='max_energy_amount',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='multiclick_amount',
        ),
        migrations.AddField(
            model_name='userdata',
            name='energy_balance',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='multiclick',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gnome_amount',
            field=models.IntegerField(default=0),
        ),
    ]
