# Generated by Django 5.0.6 on 2024-07-11 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=1.0)),
                ('asset_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates_sell', to='exchanger_app.asset')),
                ('asset_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rates_buy', to='exchanger_app.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=0.0)),
                ('amount_1', models.FloatField(default=0.0)),
                ('amount_2', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swaps_giving', to='exchanger_app.asset')),
                ('asset_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='swaps_receiving', to='exchanger_app.asset')),
            ],
        ),
    ]
