# Generated by Django 5.0.6 on 2024-07-31 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0002_initial'),
        ('levels_app', '0023_rank_swap_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='user_rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.rank'),
        ),
        migrations.CreateModel(
            name='VipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
