# Generated by Django 5.0.6 on 2024-07-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0003_swap_user_rank_vippurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangepair',
            name='fee',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
