# Generated by Django 5.0.6 on 2024-07-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger_app', '0004_exchangepair_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangepair',
            old_name='fee',
            new_name='fee_percentage',
        ),
    ]
