# Generated by Django 5.0.6 on 2024-08-07 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyBalanceUpgradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clicker_app.energybalanceupgradelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MulticlickUpgradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clicker_app.multiclickupgradelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
