# Generated by Django 5.0.6 on 2024-08-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energybalanceupgradelevel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='energybalanceupgradelevel',
            name='next_level',
        ),
        migrations.RemoveField(
            model_name='multiclickupgradelevel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='multiclickupgradelevel',
            name='next_level',
        ),
    ]
