# Generated by Django 5.0.6 on 2024-07-15 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_rename_complete_time_userstasks_completion_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.FilePathField(default='/ad1', path='./media/ads', unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.link')),
            ],
        ),
    ]
