# Generated by Django 5.0.6 on 2024-08-01 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0002_alter_advert_image_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='image_path',
            new_name='file_path',
        ),
        migrations.AddField(
            model_name='advert',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advert',
            name='relevant_region',
            field=models.CharField(choices=[('1', 'Europe'), ('2', 'India'), ('3', 'Central Asia'), ('4', 'USA and Canada'), ('5', 'Latin America'), ('6', 'Africa')], default=1),
        ),
        migrations.AddField(
            model_name='advert',
            name='show_place',
            field=models.CharField(choices=[('1', 'Banner'), ('2', 'Fairy'), ('3', 'Chest')], default=1),
        ),
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_app.advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
