# Generated by Django 5.0.6 on 2024-08-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0003_rename_image_path_advert_file_path_advert_is_video_and_more'),
        ('levels_app', '0023_rank_swap_limit'),
        ('user_app', '0014_userdata_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('relevant_region', models.CharField(choices=[('1', 'Europe'), ('2', 'India'), ('3', 'Central Asia'), ('4', 'USA and Canada'), ('5', 'Latin America'), ('6', 'Africa')], default=1)),
                ('file_path', models.FilePathField(default='ad1', path='./media/ads/', unique=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullscreenAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('relevant_region', models.CharField(choices=[('1', 'Europe'), ('2', 'India'), ('3', 'Central Asia'), ('4', 'USA and Canada'), ('5', 'Latin America'), ('6', 'Africa')], default=1)),
                ('file_path', models.FilePathField(default='ad1', path='./media/ads/', unique=True)),
                ('gnome_probability', models.FloatField(default=0.0002)),
                ('is_video', models.BooleanField(default=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.link')),
                ('view_gnome_reward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_with_gnome_reward', to='levels_app.reward')),
                ('view_gold_reward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_with_gold_reward', to='levels_app.reward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='adview',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_app.fullscreenadvert'),
        ),
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
