# Generated by Django 5.0.6 on 2024-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0004_banneradvert_fullscreenadvert_alter_adview_advert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adview',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adview',
            name='is_fairy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adview',
            name='seconds_before_click',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
