# Generated by Django 5.0.6 on 2024-08-05 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0005_adview_is_clicked_adview_is_fairy_and_more'),
        ('levels_app', '0023_rank_swap_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullscreenadvert',
            name='view_gold_reward',
        ),
        migrations.AddField(
            model_name='fullscreenadvert',
            name='view_min_gold_reward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_with_min_gold_reward', to='levels_app.reward'),
        ),
    ]
