# Generated by Django 5.0.6 on 2024-08-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0009_alter_banneradvert_link_alter_fullscreenadvert_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneradlinkclick',
            name='link',
        ),
        migrations.RemoveField(
            model_name='fullscreenadlinkclick',
            name='link',
        ),
    ]
