# Generated by Django 5.0.6 on 2024-08-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0010_remove_banneradlinkclick_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_clicks_number', models.BigIntegerField(default=0)),
                ('clicks_goal', models.BigIntegerField(blank=True, default=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_goal_reached', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads_app.banneradvert')),
                ('fullscreen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads_app.fullscreenadvert')),
            ],
        ),
        migrations.AddConstraint(
            model_name='adset',
            constraint=models.UniqueConstraint(condition=models.Q(('banner__isnull', False)), fields=('banner',), name='unique_banner'),
        ),
        migrations.AddConstraint(
            model_name='adset',
            constraint=models.UniqueConstraint(condition=models.Q(('fullscreen__isnull', False)), fields=('fullscreen',), name='unique_fullscreen'),
        ),
    ]
