# Generated by Django 5.0.6 on 2024-08-08 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0011_adset_adset_unique_banner_adset_unique_fullscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullscreenadvert',
            name='display_period',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
