# Generated by Django 5.0.6 on 2024-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSocialTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '10_Completed_Out_Rank_Tasks model',
            },
        ),
        migrations.CreateModel(
            name='MaxEnergyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '6_Energy model',
            },
        ),
        migrations.CreateModel(
            name='MulticlickLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '7_Multiplier model',
            },
        ),
        migrations.CreateModel(
            name='PassiveIncomeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '8_PassiveIncome model',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description', max_length=1023)),
                ('gold_required', models.BigIntegerField(blank=True, default=10000, null=True)),
                ('init_energy_regeneration', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '1_Rank model',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('reward_type', models.CharField(choices=[('1', 'Add gold'), ('2', 'Increase gold multiplier'), ('3', 'Add G token'), ('4', 'Replenish energy'), ('5', 'Improve passive income')], default='1', null=True)),
            ],
            options={
                'verbose_name_plural': '5_Reward model',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=1024)),
                ('reward_amount', models.BigIntegerField()),
                ('is_partner', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '9_Out_Rank_Tasks model',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '2_Stage model',
            },
        ),
        migrations.CreateModel(
            name='TaskRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField(default=0)),
                ('coord_y', models.IntegerField(default=0)),
                ('initial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '4_TaskRoutes model',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('task_type', models.CharField(choices=[('1', 'sub to channel'), ('2', 'invite friend'), ('3', 'earn N amount of gold'), ('4', 'buy energy'), ('5', 'buy pickaxe'), ('6', 'buy chest'), ('7', 'buy road')], default='6')),
                ('completion_number', models.BigIntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': '3_TaskTemplate model',
            },
        ),
    ]
