# Generated by Django 5.0.6 on 2024-07-04 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('reward_type', models.CharField(choices=[('1', 'Add gold'), ('2', 'Increase gold multiplier'), ('3', 'Add G token'), ('4', 'Replenish energy'), ('5', 'Improve passive income')], default='1', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.energylevel')),
            ],
        ),
        migrations.CreateModel(
            name='MultiplierLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.multiplierlevel')),
            ],
        ),
        migrations.CreateModel(
            name='PassiveIncomeLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.passiveincomelevel')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description', max_length=1023)),
                ('gold_required', models.BigIntegerField(blank=True, default=10000, null=True)),
                ('inviter_reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('task_type', models.CharField(choices=[('1', 'sub to channel'), ('2', 'invite friend'), ('3', 'earn N amount of gold'), ('4', 'buy energy'), ('5', 'Gnome employment(buying)'), ('6', 'upgrade pickaxe to earn more gold per click')], default='4')),
                ('completion_number', models.BigIntegerField(blank=True, null=True)),
                ('initial', models.BooleanField(default=False)),
                ('next_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.task')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.rank')),
                ('rewards', models.ManyToManyField(to='levels_app.reward')),
            ],
        ),
    ]
