# Generated by Django 5.0.6 on 2024-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='initial',
            new_name='is_free',
        ),
        migrations.RemoveField(
            model_name='task',
            name='next_task',
        ),
        migrations.AddField(
            model_name='task',
            name='block_time',
            field=models.IntegerField(default=0, help_text='time in minutes'),
        ),
        migrations.AddField(
            model_name='task',
            name='coord_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='coord_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('1', 'sub to channel'), ('2', 'invite friend'), ('3', 'earn N amount of gold'), ('4', 'buy energy'), ('5', 'Gnome employment(buying)'), ('6', 'upgrade pickaxe to earn more gold per click'), ('7', 'Unknown task')], default='4'),
        ),
    ]
