# Generated by Django 5.0.6 on 2024-07-02 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylevel',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.energylevel'),
        ),
        migrations.AlterField(
            model_name='multiplierlevel',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.multiplierlevel'),
        ),
        migrations.AlterField(
            model_name='passiveincomelevel',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.passiveincomelevel'),
        ),
    ]
