# Generated by Django 5.0.6 on 2024-07-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0002_rename_initial_task_is_free_remove_task_next_task_and_more'),
        ('user_app', '0006_remove_userdata_lang_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiplierLevel',
            new_name='MaxEnergyLevel',
        ),
        migrations.RenameModel(
            old_name='EnergyLevel',
            new_name='MulticlickLevel',
        ),
    ]
