# Generated by Django 5.0.6 on 2024-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0002_reward_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('1', 'Gold'), ('2', 'Gold_per_click'), ('3', 'G_Token')], default='1', null=True),
        ),
    ]
