# Generated by Django 5.0.6 on 2024-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("levels_app", "0002_reward_reward_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("1", "sub to channel"),
                    ("2", "invite friend"),
                    ("3", "earn N amount of gold"),
                    ("4", "buy energy"),
                    ("5", "Gnome employment(buying)"),
                    ("6", "upgrade pickaxe to earn more gold per click"),
                    ("7", "buy character to improve passive income"),
                ],
                default="4",
            ),
        ),
    ]
