# Generated by Django 5.0.6 on 2024-07-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0003_stage_next_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energylevel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
