# Generated by Django 5.0.6 on 2024-07-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0002_socialmedia_completedsocialtasks'),
        ('levels_app', '0003_rename_multiplierlevel_maxenergylevel_and_more'),
    ]

    operations = [
    ]
