# Generated by Django 5.0.6 on 2024-06-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0004_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
