# Generated by Django 5.0.6 on 2024-07-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0004_stagetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name_plural': '2.2_Stage model'},
        ),
        migrations.AlterModelOptions(
            name='stagetemplate',
            options={'verbose_name_plural': '2.1_Stage model'},
        ),
    ]
