# Generated by Django 5.0.6 on 2024-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0004_alter_energylevel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplierlevel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passiveincomelevel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
