# Generated by Django 5.0.6 on 2024-07-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0004_merge_20240709_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='rank',
        ),
        migrations.AddField(
            model_name='rank',
            name='init_energy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.maxenergylevel'),
        ),
        migrations.AddField(
            model_name='rank',
            name='init_energy_regeneration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rank',
            name='init_multiplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='levels_app.multiclicklevel'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('initial_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.task')),
                ('next_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.stage')),
                ('tasks', models.ManyToManyField(related_name='stage_tasks', to='levels_app.task')),
            ],
        ),
    ]
