# Generated by Django 5.0.6 on 2024-07-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0005_alter_multiplierlevel_id_alter_passiveincomelevel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='required_gold',
            field=models.BigIntegerField(default=10000),
        ),
    ]
