# Generated by Django 5.0.6 on 2024-07-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0005_alter_multiplierlevel_id_alter_passiveincomelevel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='rank_id',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='reward_id',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='tasks_id',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='first_stage',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='reward_id',
        ),
        migrations.AddField(
            model_name='rank',
            name='gold_required',
            field=models.BigIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.rank'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='description',
            field=models.TextField(default='No description', max_length=1023),
        ),
    ]
