# Generated by Django 5.0.6 on 2024-06-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0003_alter_reward_reward_type'),
        ('levels_app', '0005_task_amount'),
    ]

    operations = [
    ]
