# Generated by Django 5.0.6 on 2024-07-09 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0005_remove_task_rank_rank_init_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='init_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.stage'),
        ),
    ]
