# Generated by Django 5.0.6 on 2024-06-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0006_merge_0003_alter_reward_reward_type_0005_task_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('1', 'Gold'), ('2', 'Gold_per_click'), ('3', 'G_Token'), ('4', 'add gold per click + pickaxe upgrade'), ('5', 'energy balance '), ('6', 'energy balance + add gold per click'), ('7', 'add  passive income')], default='1', null=True),
        ),
    ]
