# Generated by Django 5.0.6 on 2024-07-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0006_remove_stage_next_stage_remove_stage_rank_id_and_more'),
        ('user_app', '0004_rename_rank_id_userdata_rank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
