# Generated by Django 5.0.6 on 2024-06-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0006_merge_0003_alter_reward_reward_type_0005_task_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reward_id',
        ),
        migrations.AddField(
            model_name='task',
            name='rewards',
            field=models.ManyToManyField(null=True, to='levels_app.reward'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('1', 'Add gold'), ('2', 'Increase gold per click multiplier'), ('3', 'Add G token'), ('4', 'Pickaxe upgrade'), ('5', 'Replenish energy'), ('6', 'Improve passive income')], default='1', null=True),
        ),
    ]
