# Generated by Django 5.0.6 on 2024-07-03 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0007_delete_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='inviter_reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward'),
        ),
    ]
