# Generated by Django 5.0.6 on 2024-06-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0007_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='fist_stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.stage'),
        ),
    ]
