# Generated by Django 5.0.6 on 2024-06-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0008_rank_fist_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='next_rank',
        ),
    ]
