# Generated by Django 5.0.6 on 2024-06-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0008_alter_task_rewards'),
        ('levels_app', '0009_remove_stage_next_rank'),
    ]

    operations = [
    ]
