# Generated by Django 5.0.6 on 2024-07-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0009_remove_taskroutes_subtasks_taskroutes_subtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskroutes',
            old_name='subtasks',
            new_name='parent',
        ),
    ]
