# Generated by Django 5.0.6 on 2024-07-01 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0010_merge_20240630_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_number',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rank',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward'),
        ),
    ]
