# Generated by Django 5.0.6 on 2024-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0010_merge_20240629_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
