# Generated by Django 5.0.6 on 2024-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0011_task_completion_number_alter_rank_reward_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_number',
            field=models.BigIntegerField(default=10),
        ),
    ]
