# Generated by Django 5.0.6 on 2024-06-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0011_task_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='fist_stage',
            new_name='first_stage',
        ),
    ]
