# Generated by Django 5.0.6 on 2024-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0012_alter_task_completion_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('1', 'Add gold'), ('2', 'Increase gold multiplier'), ('3', 'Add G token'), ('4', 'Replenish energy'), ('5', 'Improve passive income')], default='1', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
