# Generated by Django 5.0.6 on 2024-07-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0010_merge_20240630_1414'),
        ('levels_app', '0012_rename_fist_stage_rank_first_stage'),
    ]

    operations = [
    ]
