# Generated by Django 5.0.6 on 2024-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0012_stagetemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagetemplate',
            name='task_with_keys',
            field=models.ManyToManyField(blank=True, to='levels_app.taskroutes'),
        ),
    ]
