# Generated by Django 5.0.6 on 2024-07-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0013_merge_20240701_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='description',
            field=models.TextField(default='Some text', max_length=1023),
        ),
        migrations.AlterField(
            model_name='rank',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='reward_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.reward'),
        ),
    ]
