# Generated by Django 5.0.6 on 2024-07-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0013_alter_reward_reward_type_and_more'),
        ('levels_app', '0014_rank_description_alter_rank_reward_id_and_more'),
    ]

    operations = [
    ]
