# Generated by Django 5.0.6 on 2024-07-02 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0015_merge_20240702_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='amount',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('1', 'sub to channel'), ('2', 'invite friend'), ('3', 'earn N amount of gold'), ('4', 'buy energy'), ('5', 'Gnome employment(buying)'), ('6', 'upgrade pickaxe to earn more gold per click')], default='4'),
        ),
        migrations.CreateModel(
            name='EnergyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('next_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels_app.energylevel')),
            ],
        ),
    ]
