# Generated by Django 5.0.6 on 2024-07-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0016_remove_task_amount_alter_task_task_type_energylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='first_stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='levels_app.stage'),
        ),
    ]
