# Generated by Django 5.0.6 on 2024-07-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0016_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetemplate',
            name='jail_amount',
            field=models.IntegerField(default=1),
        ),
    ]
