# Generated by Django 5.0.6 on 2024-07-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0017_alter_rank_first_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultitapLevel',
            fields=[
                ('energylevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='levels_app.energylevel')),
            ],
            bases=('levels_app.energylevel',),
        ),
        migrations.CreateModel(
            name='PassiveIncomeLevel',
            fields=[
                ('energylevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='levels_app.energylevel')),
            ],
            bases=('levels_app.energylevel',),
        ),
        migrations.RemoveField(
            model_name='rank',
            name='next_rank',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='next_stage',
        ),
        migrations.AlterField(
            model_name='rank',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
