# Generated by Django 5.0.6 on 2024-07-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0019_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskroutes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='levels_app.taskroutes'),
        ),
    ]
