# Generated by Django 5.0.6 on 2024-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels_app', '0021_stagetemplate_has_keylock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagetemplate',
            name='has_keylock',
        ),
        migrations.AddField(
            model_name='stage',
            name='has_keylock',
            field=models.BooleanField(default=True),
        ),
    ]
